### PR TITLE
add missing e/data params in onBlur event

### PR DESCRIPTION
**Pull request by mahmoudzohdi**

### CODE REVIEW

**Comment by zabute** [comment]
Hi @mahmoudzohdi Thank you so much for this PR. Could you please rebase to master so I can merge this?

**Comment by zabute** [comment]
And don't worry about ``/lib`` we really don't need it in the repo.

**Comment by mahmoudzohdi** [comment]
Ok, I'm on my way home.
I'll do it when I get home.

**Comment by mahmoudzohdi** [comment]
@zabute  Done.

**Comment by zabute** [comment]
Thanks. Your changes have been released in 3.0.1

**Pull request merged**
