### PR TITLE
Update to formsy 2

### LINKED ISSUE #65: Preparation to formsy-react v.2
Hi,

formsy-react gonna release a major version 2, is should solve many bugs in v1.
Let's open to discussion of how would we want this lib to adjust to v2 at this thread.

I want to contribute :]

### PR DESCRIPTION
**Pull request by felixmosh**
This PR include
1.  Update to formsy v2
2. Update mocha version
3. Add missing input tests
4. Fix false positive input tests

Fixes #65

### CODE REVIEW

**Comment by zabute** [comment]
Hi @felixmosh Thank you for the pull request. I will review this as soon as i can. Apologies for the delay.

**Comment by felixmosh** [comment]
@zabute any updates?

**Comment by onomated** [comment]
@zabute Checking in on this also.  Have a static site build that's failing due to 2.0 `isPristine()` method to `isPristine` bool property changes, amongst others

**Comment by rkuykendall** [comment]
If there's anything I can do to help let me know 🙂

**Comment by felixmosh** [comment]
@zabute  ping?

**Comment by felixmosh** [comment]
Ping

**Comment by KuNman** [comment]
Bump

**Comment by felixmosh** [comment]
ping?

**Comment by rkuykendall** [comment]
@zabute Are you willing to accept additional collaborators on this project, or transfer it to the formsy org for future development?

**Comment by zabute** [comment]
Patched and Published.

**Comment by rkuykendall** [comment]
@zabute Thank you so much!

**Comment by zabute** [comment]
@rkuykendall Thank you for your work on Formsy and your sustained interest in its ecosystem.

I would be happy with having this project live in the Formsy Org if it helps prevent further hindrance to its continued maintenance. However, I would like to retain write-access to it as I'm still interested in working on it. Is that okay with you?

**Pull request merged**
